[build]
  command = "npm run build"
  publish = "build"

[[plugins]]
  package = "netlify-plugin-vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  functions = "functions"
