export const WorkData = [
  {
    title: "RESTful API for my hyper-local air quality data",
    description: "Raspberry Pi, Python, Django, PostgreSQL",
    imgSrc: "images/test.webp",
    altText: "test",
    showDemoButton: true,
    demoLink: "test",
    showGithubButton: true,
    githubRepoLink: "test",
    categories: ["software engineering"],
    showOnHomepage: true,
  },
  {
    title:
      "Driving conversions in a bite-size tattoo portfolio with booking form",
    description: "HTML, CSS, JavaScript",
    imgSrc: "/images/mahalia-xiaoqi/cover.webp",
    altText: "test",
    showCaseStudyButton: true,
    caseStudyPath: "/work/mahalia-xiaoqi",
    showGithubButton: true,
    githubRepoLink: "https://github.com/brittshook/mahalia",
    categories: ["software engineering", "UX design"],
    showOnHomepage: true,
  },
  {
    title: "Introducing Pride Pac: Queer-themed take on Pac-Man",
    description: "HTML, JavaScript",
    imgSrc: "images/test.webp",
    altText: "test",
    showDemoButton: true,
    demoLink: "test",
    showGithubButton: true,
    githubRepoLink: "https://github.com/brittshook/pride-pac",
    categories: ["software engineering"],
    showOnHomepage: true,
  },
  {
    title: "Designing a cohesive experience across platforms with StravaFit",
    description: "React, TypeScript",
    imgSrc: "images/stravafit/cover.webp",
    altText: "test",
    showCaseStudyButton: true,
    caseStudyPath: "/work/stravafit",
    showGithubButton: true,
    githubRepoLink: "https://github.com/georgeperryv/FinalStravaProject",
    categories: ["software engineering", "UX design"],
    showOnHomepage: false,
  },
  {
    title: "Leading content design for an enhanced provider experience",
    description: "State Medicaid Agency (@Deloitte Consulting)",
    imgSrc: "/images/state_medicaid_agency/cover.webp",
    altText: "test",
    showCaseStudyButton: true,
    caseStudyPath: "/work/state-medicaid-agency",
    categories: ["UX design"],
    showOnHomepage: false,
  },
];
